LICENSE.md

The current link [https://github.com/anti-work/helper/LICENSE.md](https://github.com/anti-work/helper/LICENSE.md) in the LICENSE document appears to be broken. This PR replaces it with a functioning canonical link.

chore: Fix broken LICENSE link

---

apps/tauri/src-tauri/src/lib.rs

[ref](https://anti--work.slack.com/archives/C055QQCQFM1/p1740585122481209)
Tauri's native drag and drop breaks dragging files into the reply editor.

fix: enable file drag and drop in Tauri

---

README.md
docs/development.md

Fixed incorrect script name from `bin/generate_ssl_certs` to `bin/generate_ssl_certificates` in:
- README.md
- docs/development.md
This ensures the documentation matches the actual script name in the `bin` directory.

docs: fix SSL certificate generation script name in README and development guide

---

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/dashboard/_components/realtimeEvents.tsx
apps/nextjs/src/trpc/router/mailbox/conversations/github.ts

fix : #81 
- Changed conversation ID to conversationSlug in RealtimeEvents component link.
- Updated body text in GitHub router to use conversationSlug instead of conversation ID for consistency.
https://github.com/user-attachments/assets/7c82a2e9-6032-4471-a430-4897b49f7015

fix: update conversation links in RealtimeEvents and GitHub router

---

apps/nextjs/src/components/keyboardShortcut.tsx

Doesn't work well in light mode

fix: remove background from keyboard shortcut display

---

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/search/page.tsx

fix: list item content overflow in search results

---

apps/nextjs/src/lib/data/dashboardEvent.ts
apps/nextjs/src/trpc/router/mailbox/conversations/messages.ts

Closes #115 
* Updated status query to just fetch count instead of all matching conversations
* Parallelized events query and added deletedAt check to make sure we use indexes

fix: speed up dashboard queries

---

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/[category]/layout.tsx

fix: #118 
https://github.com/user-attachments/assets/08a10777-e189-4298-abbe-3f881d9c98d8
https://github.com/user-attachments/assets/981faebd-202d-492b-b563-21eab9e4202f
https://github.com/user-attachments/assets/3926542a-1cc5-4cad-85b3-2773442bf191

fix(web): horizontroll scroll in mobile and desktop view

---

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/list.tsx

fix: squashed navbar on mobile

---

apps/nextjs/src/components/deepLinkRedirect.tsx

Prevents "Failed to execute 'removeChild'" errors by adding DOM existence checks before removing the iframe. Refactors event handling for proper cleanup of event listeners to avoid memory leaks.
Error:
```
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
at window.addEventListener.once (layout-e123562d82f1fa86.js?dpl=dpl_HKKPpzXEjz7GMaEK8XmJJxUYVt7N:1:1951)
at n (6569-7592176a73fdb837.js?dpl=dpl_HKKPpzXEjz7GMaEK8XmJJxUYVt7N:13:3642)
```

fix: iframe removal error in deep link redirection

---

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/[category]/page.tsx
apps/nextjs/src/trpc/react.tsx

Will make traces easier to understand, and we're not getting much value from these anyway. Can always add them back once we're more confident in our performance and observability.

feat: disable query batching and prefetching

---

apps/nextjs/next.config.ts

There are vastly more of these than any other transactions; they're not really useful and massively increase the number of spans we're sending.
(not 100% sure of the effect this will have, will revert if it disables more than just the middleware spans themselves)

fix: disable Sentry middleware traces

---

apps/nextjs/src/lib/data/organization.ts
apps/nextjs/src/lib/data/user.ts

Reverts antiwork/helper#122
The Clerk API doesn't seem problematic after all, and we have proper traces on Sentry now for these.

Revert "feat: benchmark Clerk API calls"

---

apps/nextjs/src/trpc/router/mailbox/index.ts

Realised the open count didn't update after I merged existing open conversations.

fix: exclude merged conversations from counts

---

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/conversation.tsx
apps/nextjs/src/inngest/functions/checkVipResponseTimes.ts
apps/nextjs/src/inngest/functions/notifyVipMessage.ts
apps/nextjs/src/lib/data/conversation.ts

[ref](https://anti--work.slack.com/archives/C085P30V4LT/p1743538005874069?thread_ts=1743537610.284869&cid=C085P30V4LT)
* Excludes merged tickets from the VIP response time alert
* Updates VIP Slack messages to link to the original ticket rather than the merged one
* Adds an overlay to merged conversations so it's obvious if something links to them

fix: VIP notifications for merged tickets

---

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/search/page.tsx
apps/nextjs/src/components/ui/badge.tsx

- Makes the search filters mobile responsive
- UI Updates to results layout, hover & selected states, badges
I combined the VIP badge and value amount with a single badge-- thinking we could scale this across the app to simplify the amount of metadata:

Fix mobile search filters + styling updates

---

apps/nextjs/src/inngest/functions/checkAssignedTicketResponseTimes.ts

[ref](https://anti--work.slack.com/archives/C08A273MA15/p1743632149497909?thread_ts=1743631201.134009&cid=C08A273MA15)

fix: filter out merged conversations from assigned tickets alert

---

apps/expo/src/types/api.ts
apps/nextjs/src/lib/data/conversationMessage.ts
apps/nextjs/src/lib/slack/shared.ts
apps/nextjs/src/trpc/router/mailbox/conversations/index.ts
apps/nextjs/tests/lib/data/conversationMessage.test.ts
apps/nextjs/tests/lib/slack/shared.test.ts

Part of #128 
Removes the current automatic signature on AI drafts; this will be replaced by the new one for all emails.
AI drafts are rarely used so we can merge this first.

feat: remove current signature feature

---

apps/nextjs/package.json
apps/nextjs/src/lib/gmail/lib.tsx
apps/nextjs/tests/lib/ai/index.test.ts
apps/nextjs/tests/lib/data/conversation.test.ts

`tsc` gives more useful output than `build` and checks more files so I often want to use it locally, but we have some type errors in test files that bloat the output.
This also adds `tsc` to the typecheck command so we get better output in CI.

chore: fix TypeScript errors in tests

---

apps/nextjs/src/inngest/functions/mergeSimilarConversations.ts

Noticed locally that merged conversations wouldn't be bumped to the top of the "Newest" list because the timestamp was still the last message in the original conversation.

fix: update lastUserEmailCreatedAt when merging conversations

---

apps/nextjs/src/lib/data/mailbox.ts
apps/nextjs/src/lib/data/organization.ts
apps/nextjs/src/lib/data/user.ts

- Cache other Clerk calls in the same request
- Remove unncessary Clerk call that is fetching the organization

fix: request cache clerk calls

---

apps/expo/src/types/api.ts
apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/conversationListContext.tsx
apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/list.tsx
apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/mobileList.tsx
apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/_components/appSidebar.tsx
apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/_components/categoryNav.tsx
apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/_components/getSidebarInfo.ts
apps/nextjs/src/trpc/router/mailbox/index.ts

- Only return the open count per status, since that’s the only one we display.
- Simplify the logic to reduce both query complexity and the total number of queries.
- Renamed tRPC query from `countByStatus` to `openCount`

fix: improve open count query

---

apps/nextjs/src/lib/slack/agent/generateAgentResponse.ts
apps/nextjs/src/lib/slack/constants.ts
apps/nextjs/tests/lib/data/mailbox.test.ts

* Apparently the permissions on install need to match the Slack app dashboard (will add a proper guide in the README later)
* Fixed broken link
* Added full current timestamp instead of just date

fix: minor bug fixes for agent

---

apps/nextjs/src/lib/slack/agent/handleMessages.ts

Fixes a bug where it would respond without a mention if you replied to a "New message from VIP customer ..." thread for example

fix: agent should only respond to threads after an explicitly mention

---

apps/nextjs/src/db/reset.ts

@raphaelcosta FYI - the enums added for `guideSessionStatus` and `guideSessionEventType` weren't dropped when resetting the database so the reset script would run into "enum already exists" errors

chore: fix db reset script to delete enums

---

apps/nextjs/src/app/api/webhooks/slack/event/route.ts
apps/nextjs/src/db/drizzle/0077_ambitious_madame_masque.sql
apps/nextjs/src/db/drizzle/meta/0077_snapshot.json
apps/nextjs/src/db/drizzle/meta/_journal.json
apps/nextjs/src/db/schema/agentMessages.ts
apps/nextjs/src/lib/slack/agent/handleMessages.ts

[ref](https://anti--work.slack.com/archives/C068HHZ64M9/p1745099354328749?thread_ts=1745074808.351449&cid=C068HHZ64M9)
Fixes a couple of wrong behaviours with the agent
* Add a unique index on user message ts so that the agent doesn't respond to the same message twice. This could happen when mentioning the agent in a thread started by the bot, which sends both `message` and `app_mention` events for the same message
* Return 200 when we don't need to handle the message to avoid Slack retrying the request

fix: stop agent from duplicating replies

---

apps/nextjs/src/inngest/client.ts
apps/nextjs/src/inngest/functions/handleSlackAgentMessage.ts
apps/nextjs/src/inngest/functions/index.ts
apps/nextjs/src/lib/slack/agent/handleMessages.ts

Will give us better observability when the agent doesn't work properly. Not sure of the latency of Inngest processing - this might make responses too slow - but worth a try to debug some issues with it not replying.

feat: move agent reply logic to Inngest job

---

apps/nextjs/src/inngest/functions/handleSlackAgentMessage.ts
apps/nextjs/src/lib/slack/agent/findMailboxForEvent.ts
apps/nextjs/src/lib/slack/agent/getThreadMessages.ts
apps/nextjs/src/lib/slack/client.ts

Fixes a bug where the agent wouldn't be able to read other bot messages since they usually send only a summary in `text` and the actual content in `blocks`.

fix: read Slack message blocks to get more context for agent

---

apps/nextjs/src/lib/slack/agent/handleMessages.ts

[ref](https://anti--work.slack.com/archives/C068HHZ64M9/p1745151598747579?thread_ts=1745074808.351449&cid=C068HHZ64M9)

fix: Slack bot should reply to its own threads unless another user is tagged

---

apps/nextjs/src/app/api/webhooks/slack/response/route.ts
apps/nextjs/src/inngest/client.ts
apps/nextjs/src/inngest/functions/handleSlackAgentMessage.ts
apps/nextjs/src/lib/ai/index.ts
apps/nextjs/src/lib/slack/agent/generateAgentResponse.ts
apps/nextjs/src/lib/slack/agent/getThreadMessages.ts
apps/nextjs/src/lib/slack/agent/handleAgentMessageSlackAction.ts
apps/nextjs/src/lib/slack/agent/handleMessages.ts

[ref](https://anti--work.slack.com/archives/C068HHZ64M9/p1745151598747579?thread_ts=1745074808.351449&cid=C068HHZ64M9)
Adds a two-step reply tool to the agent which first posts a message to confirm the text (allowing the user to edit it) and then creates the reply.
https://github.com/user-attachments/assets/abcf3e4b-3f26-44e8-b04e-4f96b4645826

feat: send replies using the agent

---

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/_components/clientLayout.tsx
apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/layout.tsx
apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/settings/_components/preferencesSetting.tsx
apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/settings/_components/settings.tsx
apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/settings/_components/themeSetting.tsx
apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/settings/page.tsx
apps/nextjs/src/components/ui/button.tsx
apps/nextjs/src/components/ui/input.tsx
apps/nextjs/src/db/schema/mailboxes.ts
apps/nextjs/src/lib/themes.ts
apps/nextjs/src/trpc/router/mailbox/preferences.ts

The most basic way to do color themes with our current CSS. We can expand this into something much nicer, but for now it allows us to play around with branded themes, local dev theme, etc.
Previews in real-time as you edit the theme, which IMO is a bad idea since you can make the site unusable, but it's the easiest preview method for now:
https://github.com/user-attachments/assets/cb4c5231-5feb-40d8-9bf5-c5203fb035e7

feat: color themes

---

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/messageActions.tsx
apps/nextjs/src/components/tiptap/editor.css
apps/nextjs/src/lib/data/conversationMessage.ts

Fixes #280 
Markdown works better in my testing than just replacing newlines.
Also added spacing to the editor styles so what you see is more similar to how it appears in the message list later.

feat: format drafts as markdown and trim whitespace

---

docs/OVERVIEW.md

Corrected a small directory URL mistake in the overview.md documentation.

Fix directory URL mistake in docs/overview.md

---

README.md

**What was added**
- Added detailed steps for installing mkcert on Windows using PowerShell and Chocolatey.
- Matched the formatting style of the macOS section to keep consistency.
- Included troubleshooting note for pre-existing Chocolatey installations.
**Why this change matters**
- This project currently only had setup instructions for macOS. By adding Windows instructions:
- We make the onboarding process smoother for contributors using Windows.
- We reduce setup time and increase accessibility for a wider developer base.
**How to test**
- Run the PowerShell script provided in the README on a Windows machine with admin rights.
- Confirm mkcert installs and runs properly with mkcert -install.

Pull Request: Add Windows setup instructions to README

---

.npmrc
bin/dev
package.json
pnpm-workspace.yaml

* `pnpm vercel` failed because dependencies weren't installed yet
* inngest-cli was failing because the postinstall script wasn't called the second time

fix: initial setup issues

---

components/widget/ChatInput.tsx

- One word messages: `"exit", "cancel", "close", "stop", "quit", "end", "bye"` will automatically close the widget.
- Messages that include the phrases `"exit chat", "exit this chat", "cancel chat", "cancel this chat"`, will automatically close the widget.
Partially addresses #360

Allow users to close the Helper widget by typing "close", "exit", "cancel", etc.

---

trpc/router/mailbox/issueGroups.ts

Joining to all conversations is a huge operation and we don't use total count anyway.

Improve common issues query performance

---

tests/e2e/conversations/conversations.spec.ts

There is no functional change in the PR. This PR just eliminated duplicate/un necessary tests. Below are the test that i removed.
1) "Should display dashboard with conversations" - we are already checking the page contains conversations in the below tests
2) "should have functional search" :- We are testing searching conversations in other tests so just checking if input is functional doesn't make sense
3) "should maintain authentication state" :- These tests are for conversation file and we already have authentication login/signup e2e tests
4) "should be responsive on mobile":- This is not really testing anything, it's just checking if "Search conversations" is visible on mobile
5) "should show truncated text for non-search results" :- …

chore: remove un necessary tests in tests/e2e/conversations/conversations.spec.ts

---

tests/e2e/team-settings/teamSettings.spec.ts

This PR combines some E2E tests together. "should invite a new team member and show it in the team list", "should allow admin to change member role".
AI Disclosure:-
No AI was used in this PR

chore: combine tests in team settings 

---

tests/e2e/conversations/commandBarActions.spec.ts
tests/e2e/conversations/conversationActions.spec.ts
tests/e2e/utils/conversationHelpers.ts
tests/e2e/utils/settingsHelpers.ts

This PR just moves command bar E2E tests out of tests/e2e/conversations/conversationActions.spec.ts
Now command bar action tests could run concurrently earlier they were limited by conversation action tests to run serially.
AI Disclosure:-
No AI was used in this PR

refactor: move command bar tests

---

tests/e2e/conversation-details/conversationDetails.spec.ts

ref:- https://github.com/antiwork/helper/issues/992
This PR merges related E2E tests and removes un necessary ones in tests/e2e/conversation-details/conversationDetails.spec.ts
I have not used any AI assistance in this PR

refactor: merge e2e tests in conversation details

---

tests/e2e/conversations/unread-messages-filter.spec.ts

This PR merges related E2E tests and removes un necessary ones in tests/e2e/conversations/unread-messages-filter.spec.ts
I have not used any AI assistance in this PR

refactor: unread message filter e2e test

---

db/schema/userProfiles.ts
lib/data/user.ts
lib/slack/agent/generateAgentResponse.ts
lib/slack/shared.ts
tests/lib/data/conversationMessage.test.ts
tests/lib/slack/shared.test.ts
tests/support/factories/users.ts

Enables auto-assignment on reply via slack
1. Agent chat
https://github.com/user-attachments/assets/9547365f-3d23-4ef2-a006-484141a04a74
2. Respond Modal
|Reply| Reply and Close|
|------|----------|
|<img width="1208" height="825" alt="reply_slack_modal" src="https://github.com/user-attachments/assets/02bf6370-c55c-41e4-838b-e9eccabcf290" />|<img width="1208" height="727" alt="reply_and_close_slack_modal" src="https://github.com/user-attachments/assets/b8615db7-78a2-493d-9408-9b7d79bdf41c" />|
1. `createReply` - auto assign behaviour with user preference enabled and disabled
2. `openRespondModal` - reply flow + reply and close flow
1. claude for slicing out parts of code from #1023
- https://github.com/antiwork/helper/issues/1008
> Slack is a good shout but tbh it's not used enough to be …

feat: enable auto-assign via slack 
