apps/nextjs/src/db/seeds/seedDatabase.ts, apps/nextjs/src/env.ts, apps/nextjs/src/lib/data/organization.ts, turbo.json
Closes #11
Replaces hardcoded strings with env vars and adds correct validation to `ENCRYPT_COLUMN_SECRET`
=> fix: make seeds easier to run

apps/nextjs/src/components/deepLinkHandler.tsx
[ref](https://anti--work.slack.com/archives/C055QQCQFM1/p1741186381877029)
=> fix: Tauri deep linking while the app is running

apps/nextjs/src/app/api/chat/conversation/route.ts, apps/nextjs/src/app/api/chat/route.ts
[ref](https://anti--work.slack.com/archives/C055QQCQFM1/p1741263834924509)
=> fix: cache prompt conversations for anonymous sessions

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/messageActions.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/ticketCommandBar/commandList.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/ticketCommandBar/index.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/ticketCommandBar/mainPage.tsx, apps/nextjs/src/components/keyboardShortcut.tsx, apps/nextjs/src/components/tiptap/editor.tsx, apps/nextjs/src/components/ui/input.tsx
Part of #3 
Changes the command bar to open inline instead of as a full screen modal, and generally moves closer to the new design.
Also restored the missing reply buttons on mobile.
https://github.com/user-attachments/assets/fc346fee-b7b5-4241-a647-b74337a96595
=> feat: inline command bar

apps/nextjs/src/db/drizzle/0062_sturdy_william_stryker.sql, apps/nextjs/src/db/drizzle/meta/0062_snapshot.json, apps/nextjs/src/db/drizzle/meta/_journal.json
- Follow-up from https://github.com/antiwork/helper/pull/57
- Remove workflow related tables
=> feat: remove workflow tables

apps/nextjs/src/app/(marketing)/_components/MarketingPage.tsx
Addresses #50 
- Updates horizontal scrolling cards to masonry grid & simplifies card implementation 
- Cards stack on mobile
=> Landing page masonry grid

apps/expo/package-lock.json, apps/expo/package.json, apps/expo/src/app/(dashboard)/_layout.tsx, apps/expo/src/app/(dashboard)/conversations/[id].tsx, apps/nextjs/src/app/(dashboard)/layout.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/conversation.tsx, apps/nextjs/src/components/nativeLinkOpener.tsx, apps/nextjs/src/components/useNativePlatform.ts
* Switched to stack navigation instead of modal
* Added native header with web <-> app communication
Fixes some awkwardness/glitches with the full-screen modal webview.
=> feat: improve mobile app conversation screen

apps/nextjs/src/components/widget/MessageElement.tsx, apps/nextjs/src/lib/ai/chat.ts, apps/nextjs/src/lib/ai/prompts.ts, apps/nextjs/src/lib/data/retrieval.ts
Resolves #61 
- Adds inline citations directly within the response text.
- Also includes a full list of sources at the end of each response for reference.
=> feat: show sources from website knowledge base

apps/expo/src/app/(dashboard)/(index)/assigned.tsx, apps/expo/src/app/(dashboard)/(index)/inbox.tsx, apps/expo/src/app/(dashboard)/(index)/index.tsx, apps/expo/src/app/(dashboard)/(index)/vips.tsx, apps/expo/src/app/(dashboard)/_components/conversationPreviewList.tsx, apps/expo/src/app/(dashboard)/_components/sidebar.tsx, apps/expo/src/app/(dashboard)/_components/tabBar.tsx, apps/expo/src/app/_layout.tsx, apps/expo/src/types/api.ts, apps/nextjs/src/trpc/router/mailbox/conversations/index.ts
Closes #89
Adds VIP and Assigned tabs with a new expanded layout:
Inline assignment:
Tabs updated on the old Inbox view:
=> feat: add VIP and assigned tabs on mobile

apps/nextjs/src/lib/ai/chat.ts
[ref](https://anti--work.slack.com/archives/C055QQCQFM1/p1742820538434929?thread_ts=1742758911.378059&cid=C055QQCQFM1)
=> fix: VIP customers still not getting AI responses to prompts

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/dashboard/layout.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/settings/layout.tsx
=> fix: scroll issue on settings and dashboard

apps/expo/src/app/(dashboard)/_components/panel.tsx, apps/expo/src/app/(dashboard)/_components/reactionsChart.tsx, apps/expo/src/app/(dashboard)/_components/statusByTypeChart.tsx, apps/expo/src/styles.css, apps/expo/src/utils/css.ts, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/dashboard/_components/dashboardAlerts.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/dashboard/_components/peopleTable.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/dashboard/_components/reactionsChart.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/dashboard/_components/realtimeEvents.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/dashboard/_components/statusByTypeChart.tsx, apps/nextjs/src/app/globals.css, apps/nextjs/src/components/panel.tsx, apps/nextjs/src/components/ui/chart.tsx
- Updated dark mode for both web & mobile
- Updated styling of realtime event cards in dark mode & removed horizontal scroll within cards
- Minor chart alignment & font size changes
- Chart color changes
<br> <br>
=> Dashboard UI improvements

apps/nextjs/src/lib/data/retrieval.ts, package-lock.json
- Remove the eager loading of messages in the similar messages query
- Related to #121
=> fix: reduce complexity of the similarity query

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/messageItem.tsx, apps/nextjs/src/db/seeds/fixtures/conversationFixture27.json, apps/nextjs/src/lib/proxyExternalContent.ts
[ref](https://anti--work.slack.com/archives/C055QQCQFM1/p1743143246497629)
=> fix: incorrect proxy replacement for inline image urls

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/messageActions.tsx
[ref](https://anti--work.slack.com/archives/C055QQCQFM1/p1740754261191159?thread_ts=1740754207.813739&cid=C055QQCQFM1)
=> fix: show cc field initially if there are cc recipients

apps/nextjs/src/app/(dashboard)/desktop/_components/tabBar.tsx, apps/nextjs/src/app/(dashboard)/desktop/signed-out/page.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/_components/appSidebar.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/settings/_components/settings.tsx, apps/tauri/src-tauri/src/lib.rs, apps/tauri/src-tauri/src/tab_manager.rs
* Fixed sign out to close all tabs and show the login page full screen
* Updated to open a new tab when you close the last one so you don't just see a blank screen
=> fix: desktop app tab behaviour fixes

apps/nextjs/src/lib/ai/chat.ts
[ref](https://anti--work.slack.com/archives/C055QQCQFM1/p1743605788435909)
=> fix: bug in load attachments

apps/nextjs/src/lib/ai/chat.ts
[ref](https://anti--work.slack.com/archives/C085P30V4LT/p1743607031260599?thread_ts=1743606923.205649&cid=C085P30V4LT)
(Likely introduced in #73)
=> fix: don't close tickets with AI responses disabled

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/eventItem.tsx, apps/nextjs/src/inngest/functions/handleAutoResponse.ts, apps/nextjs/src/inngest/functions/handleGmailWebhookEvent.ts, apps/nextjs/tests/inngest/functions/handleGmailWebhookEvent.test.ts
[ref](https://anti--work.slack.com/archives/C055QQCQFM1/p1743795454839709)
Also updated the "request_human_support" event to show a distinct description in the UI so it's clearer if this problem comes up again.
=> fix: don't set email conversations to open if they're being handled by chat

apps/nextjs/src/app/api/chat/conversation/[slug]/route.ts, apps/nextjs/src/components/widget/Message.tsx
Closes #194 
Also fixed staff messages sometimes showing HTML tags.
=> fix: "Thinking" message should not show when a human will respond

apps/nextjs/src/app/api/chat/conversation/[slug]/route.ts, apps/nextjs/src/components/widget/Conversation.tsx, apps/nextjs/src/components/widget/MessageElement.tsx, apps/nextjs/src/components/widget/useWidgetView.ts
Closes #203 
* Fixed the new conversation button to work multiple times per page load
* Updated the frontend to show the same fixed message on escalation instead of the AI-generated response. This makes it easier to trust that it's not the AI hallucinating
=> fix: improve widget UX

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/ticketCommandBar/assigneesPage.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/ticketCommandBar/mainPage.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/ticketCommandBar/previousRepliesPage.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/ticketCommandBar/types.ts
No longer shown after we made the command bar inline.
=> chore: remove unused previews from command bar

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/list.tsx, apps/nextjs/src/components/nativeAppIntegration.tsx
https://github.com/user-attachments/assets/b1d01bda-5bb6-4031-9b60-f759addcee66
Also made conversations in the list into proper links so you can open them in new tabs on desktop and web.
=> feat: context menu in desktop app

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/ticketCommandBar/toolForm.tsx
Auto-fill the email field with the email address from the conversation.
=> Auto-fill the email field for tools

apps/nextjs/src/inngest/functions/handleGmailWebhookEvent.ts
[ref](https://anti--work.slack.com/archives/C085P30V4LT/p1744228720048339?thread_ts=1744126498.204469&cid=C085P30V4LT)
=> fix: reopen inbox conversations when a new email is received

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/conversationSidebar.tsx
[ref](https://anti--work.slack.com/archives/C085P30V4LT/p1744230785832709?thread_ts=1744126498.204469&cid=C085P30V4LT)
=> fix: sort previous conversations by newest

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/conversationListContext.tsx, apps/nextjs/src/lib/ably/hooks.ts, apps/nextjs/src/lib/data/conversation.ts, apps/nextjs/tests/lib/data/conversation.test.ts
[ref](https://anti--work.slack.com/archives/C055QQCQFM1/p1744400086030649)
=> fix: decrement open conversation count more accurately

apps/nextjs/src/app/api/chat/conversation/[slug]/route.ts, apps/nextjs/src/components/widget/Conversation.tsx, apps/nextjs/src/components/widget/Message.tsx, apps/nextjs/src/components/widget/MessageElement.tsx, apps/nextjs/src/components/widget/MessagesList.tsx, apps/nextjs/src/lib/data/conversationMessage.ts
[ref](https://anti--work.slack.com/archives/C055QQCQFM1/p1744392105025959)
=> feat: show staff attachments in chat

apps/nextjs/package.json, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/sessions/[session_id]/_components/sessionDetails.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/sessions/[session_id]/_components/timeline.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/sessions/[session_id]/page.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/sessions/_components/sessionsList.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/sessions/layout.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/sessions/page.tsx, apps/nextjs/src/components/ui/toggle.tsx, apps/nextjs/src/lib/data/guide.ts, apps/nextjs/src/trpc/router/mailbox/index.ts, package-lock.json
This isn’t a production-ready version of the sessions viewer, it’s just for debugging while we test the Helping Hand with Gumroad. Most of the code was generated by AI.
- Part of #158
=> feat: helping hand sessions viewer

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/messageActions.tsx
[ref](https://anti--work.slack.com/archives/C055QQCQFM1/p1744940502870189)
=> fix: scroll not working in command bar

apps/nextjs/src/db/drizzle/0078_busy_mesmero.sql, apps/nextjs/src/db/drizzle/meta/0078_snapshot.json, apps/nextjs/src/db/drizzle/meta/_journal.json, apps/nextjs/src/db/schema/agentThreads.ts, apps/nextjs/src/lib/slack/agent/handleMessages.ts
[example](https://anti--work.slack.com/archives/C055QQCQFM1/p1745264881998269?thread_ts=1745264879.931909&cid=C055QQCQFM1)
We were checking uniqueness of the message to process for AI responses but not for the hardcoded "which mailbox" response.
=> fix: duplicate agent message asking which mailbox

apps/nextjs/src/lib/slack/agent/generateAgentResponse.ts, apps/nextjs/src/lib/slack/agent/handleMessages.ts
[ref](https://anti--work.slack.com/archives/C085P30V4LT/p1745317154289889?thread_ts=1745316001.161859&cid=C085P30V4LT)
=> fix: agent refusing to show customer emails

apps/nextjs/src/lib/ai/index.ts, apps/nextjs/src/lib/slack/agent/generateAgentResponse.ts
[ref](https://anti--work.slack.com/archives/C08A273MA15/p1745323332718309?thread_ts=1745316000.890089&cid=C08A273MA15)
=> fix: improve agent assign behaviour

apps/nextjs/src/inngest/functions/autoAssignConversation.ts
[ref](https://anti--work.slack.com/archives/C08A273MA15/p1745342751728589?thread_ts=1745338380.109099&cid=C08A273MA15)
=> fix: log reason when auto-assigning

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/_components/accountDropdown.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/_components/appSidebar.tsx, apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/settings/_components/settings.tsx, apps/nextjs/src/components/useNativePlatform.ts
[ref](https://anti--work.slack.com/archives/C055QQCQFM1/p1745360130875689)
=> fix: show full account dropdown in settings sidebar

apps/nextjs/src/auth/lib/authService.ts, apps/nextjs/tests/trpc/router/mailbox.test.ts
[ref](https://anti--work.slack.com/archives/C055QQCQFM1/p1745359328183989)
=> fix: make user core by default when creating an org

apps/nextjs/src/app/(marketing)/_components/MarketingPage.tsx, apps/nextjs/src/app/globals.css
[ref](https://anti--work.slack.com/archives/C055QQCQFM1/p1745430591354979)
=> fix: correct text color for secondary buttons in dark mode

apps/nextjs/src/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/conversationSidebar.tsx, apps/nextjs/src/app/(dashboard)/widget/test/page.tsx
=> fix: broken sidebar UI for anonymous customers

apps/nextjs/src/lib/slack/agent/generateAgentResponse.ts
[ref](https://anti--work.slack.com/archives/C068HHZ64M9/p1745680428413879?thread_ts=1745679605.299919&cid=C068HHZ64M9)
=> fix: give agent more context about who each message is from

packages/nextjs/components/widget/Header.tsx, packages/nextjs/lib/ai/guide.ts, packages/nextjs/sdk/embed.css
- Use the full-page widget for the mobile layout, just like we were doing before with the drawer
=> fix: responsive widget for mobile

packages/nextjs/components/widget/HelpingHand.tsx
- Part of https://github.com/antiwork/helper/issues/300
=> fix: remove prompt guide step

packages/nextjs/app/(embed)/widget/embed/page.tsx, packages/nextjs/components/ui/tooltip.tsx, packages/nextjs/components/widget/Header.tsx, packages/nextjs/components/widget/MessagesList.tsx, packages/nextjs/components/widget/PreviousConversations.tsx, packages/nextjs/sdk/embed.css
- Shadows
- Support → History when viewing history (Title)
- This space/gap at the bottom of message
- Remove borders of tooltips
=> fix: various widget design fixes

packages/nextjs/sdk/embed.css, packages/nextjs/sdk/index.ts
https://github.com/user-attachments/assets/28e3018c-9e58-43e8-b564-95ddb87aab70
=> feat: toggle button animation

packages/nextjs/app/(dashboard)/mailboxes/[mailbox_slug]/(inbox)/_components/newConversationModal.tsx, packages/nextjs/components/tiptap/toolbar.tsx, packages/nextjs/components/widget/ChatInput.tsx, packages/nextjs/lib/shared/browser.ts, packages/nextjs/sdk/index.ts
* Updated tooltip
* Disabled in Edge for Mac ARM since apparently it isn't supported
* Added an explicit allow microphone attribute for cross-domain iframes
=> fix: speech recognition fixes

lib/data/conversation/search.ts, lib/data/conversation/searchSchema.ts
[ref](https://anti--work.slack.com/archives/C01B70APF9P/p1746159031059029?thread_ts=1746158574.459249&cid=C01B70APF9P)
=> fix: improve agent searching for status changes

db/drizzle/0081_cold_the_liberteens.sql, db/drizzle/meta/0081_snapshot.json, db/drizzle/meta/_journal.json, tests/lib/data/mailbox.test.ts
[Slack convo](https://anti--work.slack.com/archives/C055QQCQFM1/p1746205378831629)
=> feat: add missing migration

lib/ai/tools.ts, lib/tools/apiTool.ts
[ref](https://anti--work.slack.com/archives/C055QQCQFM1/p1746509635392299)
=> fix: allow entering non-customer email in tool form

app/(dashboard)/mailboxes/[mailbox_slug]/[category]/conversation/conversation.tsx, app/(dashboard)/mailboxes/[mailbox_slug]/[category]/inbox.tsx, app/(dashboard)/mailboxes/[mailbox_slug]/[category]/tabBar.tsx
Fixes the reply buttons being pushed off the screen, and a potential error with incorrectly saved state.
=> fix: issues with standalone tab bar

lib/slack/client.ts, lib/slack/vipNotifications.ts
[ref](https://anti--work.slack.com/archives/C055QQCQFM1/p1747047136748569)
=> fix: ignore more classes of Slack error

db/drizzle/meta/0100_snapshot.json
=> fix:added missing snapshot

lib/realtime/hooks.ts, packages/client/src/realtime.ts
[Sentry](https://gumroad-to.sentry.io/issues/6737453750/?query=is%3Aunresolved&referrer=issue-stream)
=> Fix error in event listeners

lib/ai/customerInfoPrompt.ts, tests/lib/ai/customerInfoPrompt.test.ts
Should allow adding "if customer value is above zero" etc in knowledge bank.
=> Add value in customer metadata prompt

db/schema/savedReplies.ts, lib/ai/tools.ts, lib/data/savedReplies.ts, lib/slack/agent/generateAgentResponse.ts, lib/slack/agent/getThreadMessages.ts, packages/client/src/client.ts
[Slack](https://anti--work.slack.com/archives/C08A273MA15/p1756918531025749?thread_ts=1756830536.737469&cid=C08A273MA15)
Should make it nicer to put set replies in the knowledge base, i.e. "reply to tickets about X with Y saved reply"
=> Support reading saved replies in responses

.github/workflows/e2e.yml, scripts/setup-e2e-tests.sh, supabase/config.ci.toml
This PR will help reduce the CI pipeline time from 15.5 minutes to 12.5-13 minutes
AI Disclosure:-
I have Claude Code for brainstorming and planning
=> perf: e2e setup
